<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>saverestartload</AssemblyName>
    <RootNamespace>Calloatti.SaveRestartLoad</RootNamespace>
  </PropertyGroup>

  <Import Project="CommonModSettings.props" />

  <ItemGroup>
    <Publicize Include="Timberborn.CoreUI" />
  </ItemGroup>
  
</Project>